### PR TITLE
add meeting template

### PR DESCRIPTION
**Pull request by asraa**
Signed-off-by: Asra Ali <asraa@google.com>

Could you please check that the calendar link is OK?

### CODE REVIEW

**Comment by jedisct1** [comment]
Great, thanks for adding this, @asraa!

Calendar link doesn't seem to be working for me ("could not find the requested event").

**Comment by asraa** [comment]
Hmmmm I see. I made a calendar and added the meeting to it. What about this?
https://calendar.google.com/calendar/u/0?cid=Y18wbjVqN3I3MWJqY2ZsMWljdWtxNjVrZzZia0Bncm91cC5jYWxlbmRhci5nb29nbGUuY29t

**Comment by jedisct1** [comment]
That one works perfectly!

**Comment by asraa** [comment]
thanks! updated

**Review by jedisct1 — APPROVED** [review]

**Comment by asraa** [comment]
added todays notes, done adding for now!

**Pull request merged**
